### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by basti1302** [Amadox/travhaller#1]
You asked for it, so here it is :-) :

Um, I don't see the actual maze solving happening. Also, `follow` is never called, just defined. Am I missing something? It seems there should be some kind of client using the thing created by `createTravhallerNodePromise`, but I don't see it.

**Comment by marartner** [comment]
Oh right, the actual maze-solving is another thing, thats not in the repository, true. might add that as a separate repository later, as an example usage.

**Comment by basti1302** [comment]
Ah, understood. Otherwise this looks pretty slick :+1:
